name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]

jobs:
  checkout-and-setup:
    runs-on: ubuntu-latest

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Composer Install
        run: composer install

  run-laravel-pint:
    runs-on: ubuntu-latest
    needs: checkout-and-setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Laravel Pint
        run: ./vendor/bin/pint

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Laravel Pint changes
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

  run-tests:
    runs-on: ubuntu-latest
    needs: run-laravel-pint

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: ./vendor/bin/phpunit --colors=always
