name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run Laravel Pint
        run: |
          docker run --rm -v $(pwd):/var/www -w /var/www mukolla/rest-api-lumen:latest vendor/bin/pint

      - name: Run tests
        run: |
          docker run --rm -v $(pwd):/var/www -w /var/www mukolla/rest-api-lumen:latest vendor/bin/phpunit --colors=always
