name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]

jobs:
  setup-composer:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache-composer.outputs.cache-hit }}

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Composer dependencies
        id: cache-composer
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}
          restore-keys: composer-

      - name: Install Composer dependencies
        run: composer install

      - name: Save Composer vendor directory
        if: steps.cache-composer.outputs.cache-hit != 'true'
        run: echo "::set-output name=vendor-path::$(pwd)/vendor"

  run-laravel-pint:
    runs-on: ubuntu-latest
    needs: setup-composer

    permissions:
      contents: write

    steps:
      - name: Use Composer vendor from setup
        run: cp -r ${{ needs.setup-composer.outputs['vendor-path'] }} ./vendor

      - name: Run Laravel Pint
        run: ./vendor/bin/pint

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Laravel Pint changes
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

  run-tests:
    runs-on: ubuntu-latest
    needs: setup-composer

    steps:
      - name: Use Composer vendor from setup
        run: cp -r ${{ needs.setup-composer.outputs['vendor-path'] }} ./vendor

      - name: Run tests
        run: ./vendor/bin/phpunit --colors=always
